# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brandon's Website
tagline: hopefully a control theory blog
description: > # this means to ignore newlines until "baseurl:"
  My personal website. I plan on posting anything that is interesting to me here.
url: "https://braraki.github.io"

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

#About/contact:
author:
  name: Brandon Araki
  email: araki at mit dot edu
  baseurl: "" # the subpath of your site, e.g. /blog
  github_username:  braraki

# Build settings
timezone: America/New_York
enforce_ssl: braraki.github.io

markdown: kramdown

highlighter: pygments