# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brandon's Website
email: araki at mit dot edu
description: > # this means to ignore newlines until "baseurl:"
  My personal website. I plan on publishing my notes on control theory
  and related topics here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://braraki.github.io" # the base hostname & protocol for your site
#twitter_username: Idontusetwitter
github_username:  braraki

# Build settings
markdown: redcarpet

redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "autolink", "strikethrough", "with_toc_data"]
